version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - chrome
    networks:
      - app-network

  chrome:
    image: zenika/alpine-chrome:with-node
    ports:
      - "9222:9222"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
