services:
  - type: web
    name: flask-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn -w 4 -b 0.0.0.0:8080 app:app"
    envVars:
      - key: SECRET_KEY
        value: your_secret_key_here
    dockerfilePath: ./Dockerfile
