services:
  - type: web
    name: flask-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ''
    startCommand: 'flask run --host 0.0.0.0 --port 5000'
    routes:
      - src: /*
        dest: /
